---

debug: redhat_desktop

- name: Install RedHat Gnome desktop
#TODO: In theory one should be able to do this:
#yum: name="@gnome-desktop-environment" state=present
#BUT, I have been unable to get that to work, so:
  shell: yum -y groupinstall gnome-desktop-environment
  when: redhat_desktop == 'gnome'
