---

- debug: var=redhat_desktop

- name: Install RedHat Gnome desktop
  yum: name="@^gnome-desktop-environment" state=present
  when: redhat_desktop == 'gnome' or redhat_desktop == 'gnome_shell'

- name: Install RedHat KDE desktop
  yum: name="@^kde-desktop-environment" state=present
  when: redhat_desktop == 'kde'

- name: Install RedHat Cinnamon desktop
  #shell: yum --enablerepo=epel -y install cinnamon* x11
  yum: enablerepo=epel name="@^cinnamon*" state=present
  when: redhat_desktop == 'cinnamon'

- name: Install RedHat MATE desktop
  #shell: yum --enablerepo=epel -y groupinstall mate-desktop-environment x11
  yum: enablerepo=epel name="@^mate-desktop-environment" state=present
  when: redhat_desktop == 'mate'

- name: Install RedHat Xfce desktop
  #shell: yum --enablerepo=epel -y groupinstall xfce-desktop x11
  yum: enablerepo=epel name="@^xfce-desktop" state=present
  when: redhat_desktop == 'xfce'
  
- name: Install RedHat X11
  yum: name="@x11" state=present
